# Site settings

title: Mauro Marssola
description: [My documented experiences]
baseurl: ''
url: 'https://marssola.github.io'
github_username: marssola
license_url: https://raw.githubusercontent.com/marssola/marssola.github.io/main/LICENSE

# Build settings
markdown: kramdown

# use 'post' layout for posts by default (so it can be omitted in front matter)
defaults:
  -
    scope:
      path: '' # an empty string here means all files in the project
      type: 'posts' # previously `post` in Jekyll 2.2.
    values:
      layout: 'post'